service: hottakes

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  versionFunctions: false
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**
functions:
  getTwitterHottakes:
    handler: handler.getTwitterHottakes
    description: Polls for daily hottakes from twitter
    events: 
      - http:
          path: hottake/spicy/{id}
          method: get
  voteUp:
    handler: handler.voteUp
    description: Conducts an upvote on a specific hottake
    events:
      - http:
          path: hottake/spicy/{id}
          method: put
          request: 
            parameters: 
               paths: 
                 id: true
  voteDown:
    handler: handler.voteDown
    description: Conducts a downvote on a specific hottake
    events:
      - http:
          path: hottake/spicy/{id}
          method: put
          request: 
            parameters: 
               paths: 
                 id: true
  deleteTake:
    handler: handler.deleteTake
    description: deletes a hottake by id
    events:
      - http:
          path: hottake/spicy/{id}
          method: delete
          request: 
            parameters: 
              paths: 
                id: true
  getRandomTake:
    handler: handler.getRandomTake
    description: gets a random hottake from dynamodb:hottakeTable
    events:
      - http: get hottake/random
  submitHottake:
    handler: handler.submitHottake
    description: Adds user submited hottake to the hottake collection
    events:
      - http: post hottake/newtake
#    Define function environment variables here
#    environment:
#      variable2: value2

resources:  // CloudFormation template syntax
  Resources:
    HottakesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hottakeTable
        AttributeDefinitions:
          - AttributeName: origin_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: score
            AttributeType: N
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: ups
            AttributeType: N
          - AttributeName: downs
            AttributeType: N
          - AttributeName: origin
            AttributeType: S
          - AttributeName: text
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: origin_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: HottakesTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
              Resource: arn:aws:dynamodb:*:*:table/hottakeTable
        Roles:
          - Ref: IamRoleLambdaExecution     
